/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class objcPleaseDontKillMe_JNITest */

#ifndef _Included_objcPleaseDontKillMe_JNITest
#define _Included_objcPleaseDontKillMe_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     objcPleaseDontKillMe_JNITest
 * Method:    getCurrentSong
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_objcPleaseDontKillMe_JNITest_getCurrentSong
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
