/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLinkers_CurrentSongLinker */

#ifndef _Included_nativeLinkers_CurrentSongLinker
#define _Included_nativeLinkers_CurrentSongLinker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLinkers_CurrentSongLinker
 * Method:    getCurrentSongFromNativeMacPlayBack
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeLinkers_CurrentSongLinker_getCurrentSongFromNativeMacPlayBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
